# Generated by Django 4.2.10 on 2024-03-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_product', models.IntegerField()),
                ('Id_user', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('number', models.FloatField()),
                ('exp', models.FloatField()),
                ('cvv', models.FloatField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
