# Generated by Django 4.2.10 on 2024-03-10 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='Id_product',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='Id_user',
        ),
    ]
